# Day 2 (Thu, Aug 10) {- #day_2}

::: {.rmdnote}

*Locations*: [Marriott Foundation Building](#marriott-fdn-bldg) and 115 [Keller Building](#keller-bldg).

Parallel sessions for hands-on workshops. 
Locations be announced soon.

:::

## Morning {- #day_2_am}

::: {.rmdimportant}

*Theme*: How to do open science: Workshops

:::

### 08:30 am • Coffee: [Marriott Fdn Building](#marriott-fdn-bldg) {-}

### 09:00 am • Welcome to Day 2: 102 [Marriott Fdn Building](#marriott-fdn-bldg) {-}

### 09:15 am • Workshop session 1 {- #day_2_am_session_1}

| Topic | Location | Materials |
|--------------|----------|-------|
| [Data management: Policies](#howto_data_management_policies) | 102 Marriott Fdn Bldg | [Slides](pdf/2023_OpenScienceBootcamp-DataManagement.pdf) |
| [Responsible & robust research](#howto_responsible_research) | 115 Keller Bldg | [Slides]() |

### 10:15 am • Break (30 min) {-}

### 10:45 am • Workshop session 2 {- #day_2_am_session_2}

| Topic | Location | Materials |
|--------------|----------|-------|
| [Reproducible workflows with R Markdown & Quarto](#howto_rmarkdown) | 102 Marriott Fdn Bldg |  [HTML Slides](https://penn-state-open-science.github.io/bootcamp-2023-rmarkdown-quarto/) |
| [Replication studies](#howto_replication) | 115 Keller Bldg | [PDF Slides](OpenScienceBootcamp2023_McManus.pdf) |
| [Preregistration](#howto_preregistration) | Library Marriott Fdn Bldg | [Slides]() |

### 11:45 am • Lunch break: [Marriott Fdn Building](#marriott-fdn-bldg) {-}

## Afternoon {- #day_2_pm}

::: {.rmdimportant}

*Theme*: How to do open science: Workshops

:::

### 01:15 pm • Workshop session 3 {- #day_2_pm_session_3}

| Topic | Location | Materials |
|--------------|----------|-------|
| [Data management: Practicalities](#howto_data_management_practical) | 102 Marriott Fdn Bldg | [Slides]() |
| [Open science for early career researchers](#howto_early_career) | 115 Keller Bldg | [Slides]() |

### 02:15 pm • Break (30 min) {-}

### 02:45 pm • Workshop session 4 {- #day_2_pm_session_4}

| Topic | Location | Materials |
|--------------|----------|-------|
| [Intro to Jupyter notebooks](#howto_jupyter) | 115 Keller Bldg | [Notebook](html/jupyter.html) |
| [Data sharing](#howto_data_sharing) | 102 Marriott Fdn Bldg | [PDF slides](https://github.com/penn-state-open-science/bootcamp-2023-data-sharing/blob/7aef15bfc83886f488a5256cc76312cc6cf2002a/index.pdf) |

### 03:45 pm • Break to reconvene at 102 [Marriott Fdn Bldg](#marriott-fdn-bldg) {-}    

### 04:00 pm • Recap Day 2 (plenary session): 102 [Marriott Fdn Bldg](#marriott-fdn-bldg) {-}

### 04:15 pm • End of Day 2 {-}
